### ISSUE TITLE
XS71ECU1009 is superseded

### ISSUE THREAD

**Issue by csadam** [gidcs/Xenserver-Auto-Patcher#1]
The XS71ECU1009 should be removed from the XenServer71.patch file because it can kill your machine.
The XS71ECU1010 should be used instead of it. See [here](https://support.citrix.com/article/CTX231719)

**Comment by koksuanlim** [comment]
Thanks for your information.
I will remove it later.

**Comment by koksuanlim** [comment]
This issue is fixed on 0ad938518d7482f72c257d3078eb1d54f17d5227 and c008054540d1ae69ac707d5f6c11c4925883fb8f.
