### ISSUE TITLE
Hotfix XS70E005 in included in Hotfix XS70E030 - For XenServer 7.0

### ISSUE THREAD

**Issue by csadam** [gidcs/Xenserver-Auto-Patcher#3]
Hotfix XS70E005 should be skipped for XS 7.0.
As written in: [CTX223825 Hotfix XS70E030 - For XenServer 7.0](https://support.citrix.com/article/CTX223825)

> After applying Hotfix XS70E005 the sm-multipath is removed from the list of services. The removal of sm-multipath is observed only when the XenServer host restarts. If the root disk is managed by multipath, then the number of paths reported by it can possibly be incorrect.
> 
> This hotfix also includes the following previously released hotfix:
>     CTX215416 - Hotfix XS70E005 - For XenServer 7.0

**Comment by koksuanlim** [comment]
Thanks. I have fix it.
